on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: a
            b
            c
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World "
      - run: |
          echo "${{ steps.issue.outputs.issue }}"
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $hello
